sistema/src/main/java/br/com/vle/controller/pessoa/PessoaController.java
package br.com.vle.controller.pessoa;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.enterprise.context.Conversation;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.event.Event;
import javax.faces.event.ActionEvent;
import javax.faces.event.AjaxBehaviorEvent;
import javax.inject.Inject;
import javax.inject.Named;

import br.com.vle.comum.ControllerBase;
import br.com.vle.comum.Pages;
import br.com.vle.controller.perfilacesso.Eventos;
import br.com.vle.entidade.Pessoa;
import br.com.vle.entidade.Usuario;
import br.com.vle.enuns.EstadosEnum;
import br.com.vle.enuns.StatusEnum;
import br.com.vle.model.ModelPessoa;
import br.com.vle.servico.dao.DaoPessoa;
import br.com.vle.servico.dao.DaoUsuario;
import br.com.vle.util.ValidatorUtils;

/**
 *
 * @author Victor Godoi
 */

@Named
@RequestScoped
public class PessoaController extends ControllerBase {

	private static final long serialVersionUID = 8776100090021916640L;
	
    @Inject
	private Conversation conversation;

	@Inject
	private transient Logger logger;
	
	@Inject
	private ModelPessoa modelPessoa;
	
	@Inject
	private DaoUsuario daoUsuario;
	
	@Inject
	private DaoPessoa daoPessoa;
	
	@Inject 
	private Event<Eventos> events;
	
	@PostConstruct
	public void init() {
		logger.info("=====================================");
		logger.info("=====  Start Pessoa Controller  =====");
		logger.info("=====================================");
		
	}
	
	@PreDestroy
	public void destroi(){
		logger.info("====================================");
		logger.info("=====  Stop Pessoa Controller  =====");
		logger.info("====================================");
	}
	
	public StatusEnum[] getStatus(){
		return StatusEnum.values();
	}

	public void limpaConsulta(ActionEvent actionEvent){ 
		modelPessoa.setCpfCnpj(null);
		modelPessoa.setNome(null);
		modelPessoa.setStatus(null);
		modelPessoa.setPerfilUsuario(null);
	}
    
    /**
     * @return
     */
    public String novaPessoa(){
    			
    			return redirect(Pages.MANTER_PESSOA_INCLUIR);
    			
    }
    
    /**
     * @param pessoa
     */
    public String selecionar(){
    	
    	if(modelPessoa.getPessoaSelecionado() == null){
    		messageErro("pessoa_msg_selecionar");
    		return null;
    	}
    	
    	return voltar();
    }
    
    /**
     * @param pessoa
     */
    public String abrirAlterar(Pessoa pessoa){
    	
    	EstadosEnum[] estados = EstadosEnum.values();
    	
    	for (EstadosEnum estado: estados) {
    		
    		if(estado.getUf().toString().equals(pessoa.getSsp())) {
    			modelPessoa.setEstado(estado);
    			break;
    		}
    	}
    	
    	modelPessoa.setPessoaSelecionado(pessoa);
    	modelPessoa.setUsuarioSelecionado(buscaUsuario(pessoa.getCpfCnpj().toString()));
    	modelPessoa.setPerfilUsuario(modelPessoa.getUsuarioSelecionado().getPerfilAcesso());
    	
    	return redirect(Pages.MANTER_PESSOA_ALTERAR);
    	
    }
 
    public void prepara(){
    	
    	if(conversation.isTransient())
    		conversation.begin();
    	
    }


	/**
	 * @param pessoa
	 */
	public String ativarUsuario(Pessoa pessoa) {
		
		Usuario usu  = buscaUsuario(pessoa.getCpfCnpj().toString());
		
		daoPessoa.desbloqueio(pessoa);
		daoUsuario.desbloqueio(usu);
		messageInfo("Pessoa ativada com sucesso.");
		return redirect(Pages.MANTER_PESSOA);
	}
	
	/**
	 * @param usuario
	 */
	public String inativarUsuario(Pessoa pessoa) {
		
		Usuario usu  = buscaUsuario(pessoa.getCpfCnpj().toString());
		
		daoPessoa.bloqueio(pessoa);
		daoUsuario.bloqueio(usu);
		messageInfo("Pessoa bloqueado com sucesso.");
		return redirect(Pages.MANTER_PESSOA);
	}
	
	/**
	 * 
	 * @param actionEvent
	 */
	public String inativarSelecionados(AjaxBehaviorEvent event) {
		
		if(modelPessoa.getSelecionados() == null || modelPessoa.getSelecionados().length <= 0){
			messageWarn("Nenhum registro foi selecionado.");
			return redirect(Pages.MANTER_PESSOA);
		}
		
		
		listarUsuarios();
		
		int qtd = modelPessoa.getUsuariosSelecionados().size();
		daoUsuario.bloqueio(modelPessoa.getUsuariosSelecionados());
		messageInfo("Foi(ram) Bloqueado(s) "+qtd+" registro(s) com sucesso.");
		
		return redirect(Pages.MANTER_PESSOA);
		
	}
	
	/**
	 * 
	 * @param actionEvent
	 */
	public String ativarSelecionados(AjaxBehaviorEvent event) {
		
		if(modelPessoa.getSelecionados() == null || modelPessoa.getSelecionados().length <= 0){
			messageWarn("Nenhum registro foi selecionado.");
			return redirect(Pages.MANTER_PESSOA);
		}
		
		listarUsuarios();
		
		int qtd = modelPessoa.getUsuariosSelecionados().size();
		daoUsuario.desbloqueio(modelPessoa.getUsuariosSelecionados());
		messageInfo("Foi(ram) Bloqueado(s) "+qtd+" registro(s) com sucesso.");
		
		return redirect(Pages.MANTER_PESSOA);
		
	} 
	
	public void listarUsuarios(){
		
		List <Usuario> usuarios = new ArrayList();		
	
		for(Pessoa pessoa:modelPessoa.getSelecionados()) {
			
			for(Usuario usuario: modelPessoa.getUsuarios()) {
				
				if(pessoa.getCpfCnpj().toString().equals(usuario.getId().toString())) {
					usuarios.add(usuario);
				}
			}
		}
		modelPessoa.setUsuariosSelecionados(usuarios);
	}
	
	public Usuario buscaUsuario(String id) {
		
		Usuario usu = null;
		
		for(Usuario usuario :modelPessoa.getUsuarios()) {
			
			if(usuario.getId().trim().length()<11 || usuario.getId().trim().length()>11 || usuario.getId().trim().length()<14) {
				usuario.setId(adicionaZero(usuario.getId()));
			}
			
			if(usuario.getId().toString().equals(id)) {
				usu = usuario;
				break;
			}
		}
		
		return usu;
	}
	
	public StatusEnum[] getListaStatus(){
		return StatusEnum.values();
	}
	
	public String adicionaZero(String cpfCnpj){
	
		while(cpfCnpj.trim().length() <= 10) {
			cpfCnpj = "0" + cpfCnpj.toString();
			
		}
		
		while(cpfCnpj.trim().length() > 11 && cpfCnpj.trim().length() <=13) {
			cpfCnpj = "0" + cpfCnpj.toString();
			
		}
		
		return cpfCnpj;
	}

}

sistema/src/main/webapp/WEB-INF/page/manterpessoa/manter_pessoa_lista.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<ui:composition template="/templates/layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="centroMeio">
		<p:panelGrid columns="1" style="margin:0 auto;width:100%;">

			<f:facet name="header">
			#{msg['pessoa_menu']}
		</f:facet>

			<h:form id="formconsulta">
				<p:growl autoUpdate="true" globalOnly="true" sticky="false" />
				<p:panelGrid columns="2" cellpadding="4" style="margin:0 auto;">

					<h:outputText value="#{msg['usuario_nome']} :" />
					<h:panelGroup>
						<h:message for="itNome" styleClass="error" />
						<h:inputText maxlength="60" size="51" id="itNome" required="false"
							label="#{msg['pessoa_nome']}" value="#{modelPessoa.nome}">
							<f:converter converterId="br.com.vle.util.CaixaAltaConverter" />
						</h:inputText>
					</h:panelGroup>

					<h:outputText value="#{msg['pessoa_cpf_cnpj']} :" />
					<h:panelGroup>
						<h:message for="itcpfCnpj" styleClass="error" />
						<h:inputText maxlength="14" size="21" id="itcpfCnpj"
							value="#{modelPessoa.cpfCnpj}" required="false">
						</h:inputText>
					</h:panelGroup>

					<h:outputText value="#{msg['usuario_status']} :" />
					<h:panelGroup>
						<h:message for="itStatus" styleClass="error" />
						<h:selectOneMenu id="itStatus" required="true"
							value="#{modelPessoa.status}" style="width: 160px; height: 30px;">
							<f:selectItems value="#{pessoaController.listaStatus}" var="item"
								itemValue="#{item}" />
						</h:selectOneMenu>
					</h:panelGroup>

					<f:facet name="footer">

						<p:commandButton value="#{msg['pessoa_novo']}"
							rendered="#{request.isUserInRole('manter_pessoa_incluir')}"
							action="#{pessoaController.novaPessoa()}"
							update="formconsulta"
							title="#{msg['usuario_novo_title']}">
						</p:commandButton>

						<p:commandButton value="#{msg['pessoa_consultar']}"
							title="#{msg['pessoa_consultar']}" update=":formResultado">
						</p:commandButton>

						<p:commandButton value="#{msg['pessoa_limpar']}"
							title="#{msg['pessoa_limpar']}"
							actionListener="#{pessoaController.limpaConsulta}" />

					</f:facet>

				</p:panelGrid>
			</h:form>

			<h:form id="formResultado">
				<p:growl autoUpdate="true" globalOnly="true" sticky="false" />
				<p:dataTable id="dataTable" var="pessoa"
					emptyMessage="#{msg['sem_registro']}"
					value="#{modelPessoa.lazyModel}" paginator="true"
					rows="#{modelPessoa.qtdRows}"
					first="#{modelPessoa.pageSelecionada}"
					selection="#{modelPessoa.selecionados}"
					paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}  {RowsPerPageDropdown}"
					currentPageReportTemplate="#{msg['paginacao']}" lazy="true"
					rowsPerPageTemplate="5,10,15,50,100" rowIndexVar="x">

					<f:facet name="header">
                   #{msg['pessoa_titulo_lista']}
					</f:facet>

					<p:column selectionMode="multiple" style="width:18px" />

					<p:column sortBy="#{pessoa.nome}">
						<f:facet name="header">
							<h:outputText value="#{msg['pessoa_nome']}" />
						</f:facet>
						<h:outputText value="#{pessoa.nome}" title="#{pessoa.nome}" />
					</p:column>

					<p:column sortBy="#{pessoa.cpfCnpj}">
						<f:facet name="header">
							<h:outputText value="#{msg['pessoa_cpf_cnpj']}" />
						</f:facet>
						<h:outputText value="#{pessoa.cpfCnpj}" />
					</p:column>

					<p:column sortBy="#{pessoa.email}">
						<f:facet name="header">
							<h:outputText value="#{msg['pessoa_email']}" />
						</f:facet>
						<h:outputText value="#{pessoa.email}" />
					</p:column>

					<p:column sortBy="#{pessoa.dtCadastro}">
						<f:facet name="header">
							<h:outputText value="#{msg['pessoa_data_cadastro']}" />
						</f:facet>
						<h:outputText value="#{pessoa.dtCadastro}">
						<f:convertDateTime pattern="dd/MM/yyyy" />
						</h:outputText>
					</p:column>

					<p:column sortBy="#{pessoa.ativo}">
						<f:facet name="header">
							<h:outputText value="#{msg['pessoa_status']}" />
						</f:facet>
						<h:outputText rendered="#{!pessoa.ativo}" value="#{pessoa.ativo}">
							<f:converter converterId="br.com.vle.util.StatusConverter" />
						</h:outputText>
						<h:outputText rendered="#{pessoa.ativo}" value="#{pessoa.ativo}">
							<f:converter converterId="br.com.vle.util.StatusConverter" />
						</h:outputText>
					</p:column>

					<p:column width="50ps">
						<f:facet name="header">
							<h:outputText value="#{msg['pessoa_acao']}" />
						</f:facet>
						<h:panelGroup>

							<p:commandButton icon="ui-icon-pencil"
								rendered="#{request.isUserInRole('manter_pessoa_alterar')}"
								action="#{pessoaController.abrirAlterar(pessoa)}"
								update=":formResultado" title="#{msg['pessoa_acao_alterar']}">
							</p:commandButton>

							<p:commandButton
								action="#{pessoaController.inativarUsuario(pessoa)}"
								rendered="#{request.isUserInRole('manter_pessoa_bloquear')}"
								icon="ui-icon-locked" update="dataTable"
								title="#{msg['pessoa_acao_inativar']}">
							</p:commandButton>

							<p:commandButton
								action="#{pessoaController.ativarUsuario(pessoa)}"
								rendered="#{request.isUserInRole('manter_pessoa_desbloquear')}"
								icon="ui-icon-unlocked" update="dataTable"
								title="#{msg['pessoa_acao_ativar']}">
							</p:commandButton>

						</h:panelGroup>
					</p:column>

				</p:dataTable>
				<p:panelGrid columns="2" style="width: 100%">
					<f:facet name="footer">
						<p:growl />
						<p:commandButton value="#{msg['pessoa_acao_inativar_lote']}"
							rendered="#{request.isUserInRole('manter_pessoa_bloquear')}"
							title="#{msg['pessoa_acao_inativar_lote_title']}">
							<f:ajax execute=":formResultado" render=":formResultado"
								listener="#{pessoaController.inativarSelecionados}" />
						</p:commandButton>

						<p:commandButton value="#{msg['pessoa_acao_ativar_lote']}"
							rendered="#{request.isUserInRole('manter_pessoa_desbloquear')}"
							title="#{msg['pessoa_acao_ativar_lote_title']}">
							<f:ajax execute=":formResultado" render=":formResultado"
								listener="#{pessoaController.ativarSelecionados}" />
						</p:commandButton>
					</f:facet>
				</p:panelGrid>
			</h:form>
		</p:panelGrid>
	</ui:define>

	<ui:define name="centroRodapeSemLayout" />
	<ui:define name="direitaSemLayout" />
	<ui:debug hotkey="x" />

</ui:composition>

sistema/src/main/webapp/WEB-INF/page/manterpessoa/manter_pessoa_selecao.xhtml
<?xml version="1.0" encoding="UTF-8" ?>  
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">  
<ui:composition template="/templates/layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	
	<ui:define name="centroMeio">
		<p:panelGrid columns="1" style="margin:0 auto;width:100%;">
			
			<f:facet name="header">
				#{msg['pessoa_menu_selecionar']}
			</f:facet>
		
			<h:form id="formconsulta">	
				<p:growl autoUpdate="true" globalOnly="true" />	
				<p:panelGrid columns="2"  cellpadding="4" style="margin:0 auto;">
				
					<h:outputText value="#{msg['usuario_nome']} :" />
					<h:panelGroup>
						<h:message for="itNome" styleClass="error" />
						<h:inputText maxlength="60" size="51" id="itNome"
							label="#{msg['pessoa_nome']}" value="#{modelPessoa.nome}">
							<f:converter converterId="br.com.vle.util.CaixaAltaConverter" />
						</h:inputText>
					</h:panelGroup>

					<h:outputText value="#{msg['pessoa_cpf_cnpj']} :" />
					<h:panelGroup>
						<h:message for="itcpfCnpj" styleClass="error" />
						<h:inputText maxlength="14" size="21" id="itcpfCnpj"
							value="#{modelPessoa.cpfCnpj}">
						</h:inputText>
					</h:panelGroup>

					<h:outputText value="#{msg['usuario_perfil']} :" />
					<h:panelGroup>
						<h:message for="itperfil" styleClass="error" />
						<h:selectOneMenu id="itperfil" required="true"
							style="width: 160px; height: 30px;" label="Perfil"
							value="#{modelPessoa.perfilUsuario}">
							<f:selectItems value="#{modelPessoa.perfis}" var="_perfil"
								itemValue="#{_perfil}" itemLabel="#{_perfil.perfil}" />
							<f:converter converterId="br.com.vle.util.ObjectConverter" />
						</h:selectOneMenu>
					</h:panelGroup>


					<h:outputText value="#{msg['usuario_status']} :" />
					<h:panelGroup>
						<h:message for="itStatus" styleClass="error" />
						<h:selectOneMenu id="Status" required="true"
							value="#{modelPessoa.status}" style="width: 160px; height: 30px;">
							<f:selectItems value="#{pessoaController.listaStatus}" var="item"
								itemValue="#{item}" />
						</h:selectOneMenu>
					</h:panelGroup>
				
					<f:facet name="footer">
						
						<!--p:commandButton value="#{msg['perfil_novo']}"
							action="#{perfilController.novoPerfil()}"
							title="#{msg['perfil_title_novo']}">
						</p:commandButton-->
					
						<p:commandButton value="#{msg['pessoa_consultar']}"
							title="#{msg['pessoa_title_consultar']}"
							update=":formResultado">
						</p:commandButton>
					
					</f:facet>	
					
				</p:panelGrid>
			</h:form>	
				
			
			
<h:form id="formResultado">
				<p:growl autoUpdate="true" globalOnly="true" sticky="false" />
				<p:dataTable id="dataTable" var="pessoa"
					emptyMessage="#{msg['sem_registro']}"
					value="#{modelPessoa.lazyModel}" paginator="true"
					rows="#{modelPessoa.qtdRows}"
					first="#{modelPessoa.pageSelecionada}"
					selection="#{modelPessoa.selecionados}"
					paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}  {RowsPerPageDropdown}"
					currentPageReportTemplate="#{msg['paginacao']}" lazy="true"
					rowsPerPageTemplate="5,10,15,50,100" rowIndexVar="x">

					<f:facet name="header">
                   #{msg['pessoa_titulo_lista']}
					</f:facet>

					<p:column selectionMode="multiple" style="width:18px" />

					<p:column sortBy="#{pessoa.nome}">
						<f:facet name="header">
							<h:outputText value="#{msg['pessoa_nome']}" />
						</f:facet>
						<h:outputText value="#{pessoa.nome}" title="#{pessoa.nome}" />
					</p:column>

					<p:column sortBy="#{pessoa.cpfCnpj}">
						<f:facet name="header">
							<h:outputText value="#{msg['pessoa_cpf_cnpj']}" />
						</f:facet>
						<h:outputText value="#{pessoa.cpfCnpj}" />
					</p:column>

					<p:column sortBy="#{pessoa.email}">
						<f:facet name="header">
							<h:outputText value="#{msg['pessoa_email']}" />
						</f:facet>
						<h:outputText value="#{pessoa.email}" />
					</p:column>

					<p:column sortBy="#{pessoa.dtCadastro}">
						<f:facet name="header">
							<h:outputText value="#{msg['pessoa_data_cadastro']}" />
						</f:facet>
						<h:outputText value="#{pessoa.dtCadastro}" pattern="dd/MM/aaaa" />
					</p:column>

					<p:column sortBy="#{pessoa.ativo}">
						<f:facet name="header">
							<h:outputText value="#{msg['pessoa_status']}" />
						</f:facet>
						<h:outputText rendered="#{!pessoa.ativo}" value="#{pessoa.ativo}">
							<f:converter converterId="br.com.vle.util.StatusConverter" />
						</h:outputText>
						<!--h:outputText rendered="#{pessoa.ativo}" value="#{pessoa.ativo}">
							<f:converter converterId="br.com.vle.util.StatusConverter" />
						</h:outputText-->
					</p:column>
	
					<!--p:column width="50ps">
						<f:facet name="header">
							<h:outputText value="#{msg['perfil_acao']}" />
						</f:facet>
						<h:panelGroup>
						
							<p:commandButton 
								icon="ui-icon-pencil"
								rendered="#{request.isUserInRole('manter_perfil_acesso_alterar')}"
								action="#{perfilController.abrirAlterar(perfil)}"
								title=" #{msg['perfil_title_acao_alterar']} " >
							</p:commandButton>
							
							<p:commandButton 
								action="#{perfilController.doDelete(perfil)}"
								rendered="#{request.isUserInRole('manter_perfil_acesso_apagar')}"
								icon="ui-icon-trash" 
								update="dataTable"
								title="#{msg['perfil_title_acao_apagar']}">
							</p:commandButton>
							
						</h:panelGroup>
					</p:column-->
					
					<f:facet name="footer">
						<p:commandButton value="#{msg['pessoa_selecionar']}"
							action="#{incluirContratosController.selecionarPessoa()}"
							title="#{msg['pessoa_selecionar']}">
							<f:ajax execute=":formResultado" render="dataTable"/>
						</p:commandButton>
	                </f:facet>
					
				</p:dataTable>
			</h:form>
		
		</p:panelGrid>
	
	</ui:define>

	<ui:define name="centroRodapeSemLayout"/>
	<ui:define name="direitaSemLayout"/>
	
</ui:composition>