sistema/src/main/java/br/com/vle/model/ModelImoveis.java
package br.com.vle.model;

import java.io.Serializable;
import java.util.List;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.LazyDataModel;
import org.primefaces.model.UploadedFile;

import br.com.vle.controller.imoveis.DataModelImoveis;
import br.com.vle.entidade.Imoveis;
import br.com.vle.enuns.StatusImoveisEnum;
import br.com.vle.enuns.TipoImovelEnum;
import br.com.vle.servico.dao.DaoImoveis;

/**
 *
 * @author Victor Godoi
 */

@Named
@ConversationScoped
public class ModelImoveis implements Serializable {

	private static final long serialVersionUID = 1110248501652831575L;
	
	@Inject
	private Conversation conversation;
	
	@Inject
	private transient Logger logger;
	
	private List<UploadedFile>  Imagens;
	
	private UploadedFile  Imagen;
	
	private Imoveis imovelSelecionado;
	
	private Imoveis imovel;

	private List <Imoveis> imoveis;
	
	@Inject
	private DaoImoveis daoImoveis;
	
	private LazyDataModel<Imoveis> lazyModel;
	
	private Integer pageSelecionada;
	
	private Integer qtdRows = 10;
	
	private TipoImovelEnum tpImovel;
	
	private StatusImoveisEnum statusImovel;
	
	private String cep;
	@PostConstruct
	public void init() {
		logger.info("====================================");
		logger.info("=======  Start Model Imoveis  =======");
		logger.info("=  conversation = "+conversation.getId());
		
		if(conversation.isTransient()){
			logger.info("==  conversation begin             ==");
			conversation.begin();
			conversation.setTimeout(60 * 60 * 1000);
		}
		
		logger.info("=  conversation = "+conversation.getId());
		logger.info("====================================");
		
		if(this.imovel == null) {
			this.imovel =  new Imoveis();
		}
		
		lazyModel = new DataModelImoveis(this, daoImoveis);
	}
	
	@PreDestroy
	public void destroi(){
		logger.info("=====================================");
		logger.info("========  Stop Model Imoveis  ========");
		
		if(!conversation.isTransient()){
			logger.info("==  conversation end             ==");
			conversation.end();
		}
		
		logger.info("====================================");
	}

	public Conversation getConversation() {
		return conversation;
	}

	public void setConversation(Conversation conversation) {
		this.conversation = conversation;
	}

	public Imoveis getImovelSelecionado() {
		return imovelSelecionado;
	}

	public void setImovelSelecionado(Imoveis imovelSelecionado) {
		this.imovelSelecionado = imovelSelecionado;
	}

	public List<UploadedFile> getImagens() {
		return Imagens;
	}

	public void setImagens(List<UploadedFile> img) {
		Imagens = img;
	}
	
	public UploadedFile getImagen() {
		return Imagen;
	}

	public void setImagen(UploadedFile img) {
		Imagen = img;
	}

	public List<Imoveis> getImoveis() {
		return imoveis;
	}

	public void setImoveis(List<Imoveis> imoveis) {
		this.imoveis = imoveis;
	}

	public Imoveis getImovel() {
		return imovel;
	}

	public void setImovel(Imoveis imovel) {
		this.imovel = imovel;
	}

	public LazyDataModel<Imoveis> getLazyModel() {
		return lazyModel;
	}

	public void setLazyModel(LazyDataModel<Imoveis> lazyModel) {
		this.lazyModel = lazyModel;
	}

	public Integer getPageSelecionada() {
		return pageSelecionada;
	}

	public void setPageSelecionada(Integer pageSelecionada) {
		this.pageSelecionada = pageSelecionada;
	}

	public Integer getQtdRows() {
		return qtdRows;
	}

	public void setQtdRows(Integer qtdRows) {
		this.qtdRows = qtdRows;
	}

	public TipoImovelEnum[] getListatpImoveis() {
		return TipoImovelEnum.values();
	}


	public TipoImovelEnum getTpImovel() {
		return tpImovel;
	}

	public void setTpImovel(TipoImovelEnum tpImovel) {
		this.tpImovel = tpImovel;
	}

	public StatusImoveisEnum[] getListaStatusImoveis() {
		return StatusImoveisEnum.values();
	}

	public StatusImoveisEnum getStatusImovel() {
		return statusImovel;
	}

	public void setStatusImovel(StatusImoveisEnum statusImovel) {
		this.statusImovel = statusImovel;
	}

	public String getCep() {
		return cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}
	
	
	
}

sistema/src/main/java/br/com/vle/controller/pessoa/PessoaController.java
package br.com.vle.controller.pessoa;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.enterprise.context.Conversation;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.event.Event;
import javax.faces.event.ActionEvent;
import javax.faces.event.AjaxBehaviorEvent;
import javax.inject.Inject;
import javax.inject.Named;

import br.com.vle.comum.ControllerBase;
import br.com.vle.comum.Pages;
import br.com.vle.controller.perfilacesso.Eventos;
import br.com.vle.entidade.Pessoa;
import br.com.vle.entidade.Usuario;
import br.com.vle.enuns.EstadosEnum;
import br.com.vle.enuns.StatusEnum;
import br.com.vle.model.ModelPessoa;
import br.com.vle.servico.dao.DaoPessoa;
import br.com.vle.servico.dao.DaoUsuario;
import br.com.vle.util.ValidatorUtils;

/**
 *
 * @author Victor Godoi
 */

@Named
@RequestScoped
public class PessoaController extends ControllerBase {

	private static final long serialVersionUID = 8776100090021916640L;
	
    @Inject
	private Conversation conversation;

	@Inject
	private transient Logger logger;
	
	@Inject
	private ModelPessoa modelPessoa;
	
	@Inject
	private DaoUsuario daoUsuario;
	
	@Inject
	private DaoPessoa daoPessoa;
	
	@Inject 
	private Event<Eventos> events;
	
	@PostConstruct
	public void init() {
		logger.info("=====================================");
		logger.info("=====  Start Pessoa Controller  =====");
		logger.info("=====================================");
		
	}
	
	@PreDestroy
	public void destroi(){
		logger.info("====================================");
		logger.info("=====  Stop Pessoa Controller  =====");
		logger.info("====================================");
	}
	
	public StatusEnum[] getStatus(){
		return StatusEnum.values();
	}

	public void limpaConsulta(ActionEvent actionEvent){ 
		modelPessoa.setCpfCnpj(null);
		modelPessoa.setNome(null);
		modelPessoa.setStatus(null);
		modelPessoa.setPerfilUsuario(null);
	}
    
    /**
     * @return
     */
    public String novaPessoa(){
    			
    			return redirect(Pages.MANTER_PESSOA_INCLUIR);
    			
    }
    
    /**
     * @param pessoa
     */
    public String selecionar(){
    	
    	if(modelPessoa.getPessoaSelecionado() == null){
    		messageErro("pessoa_msg_selecionar");
    		return null;
    	}
    	
    	return voltar();
    }
    
    /**
     * @param pessoa
     */
    public String abrirAlterar(Pessoa pessoa){
    	
    	EstadosEnum[] estados = EstadosEnum.values();
    	
    	for (EstadosEnum estado: estados) {
    		
    		if(estado.getUf().toString().equals(pessoa.getSsp())) {
    			modelPessoa.setEstado(estado);
    			break;
    		}
    	}
    	
    	modelPessoa.setPessoaSelecionado(pessoa);
    	modelPessoa.setUsuarioSelecionado(buscaUsuario(pessoa.getCpfCnpj().toString()));
    	modelPessoa.setPerfilUsuario(modelPessoa.getUsuarioSelecionado().getPerfilAcesso());
    	
    	return redirect(Pages.MANTER_PESSOA_ALTERAR);
    	
    }
 
    public void prepara(){
    	
    	if(conversation.isTransient())
    		conversation.begin();
    	
    }


	/**
	 * @param pessoa
	 */
	public String ativarUsuario(Pessoa pessoa) {
		
		Usuario usu  = buscaUsuario(pessoa.getCpfCnpj().toString());
		
		daoPessoa.desbloqueio(pessoa);
		daoUsuario.desbloqueio(usu);
		messageInfo("Pessoa ativada com sucesso.");
		return redirect(Pages.MANTER_PESSOA);
	}
	
	/**
	 * @param usuario
	 */
	public String inativarUsuario(Pessoa pessoa) {
		
		Usuario usu  = buscaUsuario(pessoa.getCpfCnpj().toString());
		
		daoPessoa.bloqueio(pessoa);
		daoUsuario.bloqueio(usu);
		messageInfo("Pessoa bloqueado com sucesso.");
		return redirect(Pages.MANTER_PESSOA);
	}
	
	/**
	 * 
	 * @param actionEvent
	 */
	public String inativarSelecionados(AjaxBehaviorEvent event) {
		
		if(modelPessoa.getSelecionados() == null || modelPessoa.getSelecionados().length <= 0){
			messageWarn("Nenhum registro foi selecionado.");
			return redirect(Pages.MANTER_PESSOA);
		}
		
		
		listarUsuarios();
		
		int qtd = modelPessoa.getUsuariosSelecionados().size();
		daoUsuario.bloqueio(modelPessoa.getUsuariosSelecionados());
		messageInfo("Foi(ram) Bloqueado(s) "+qtd+" registro(s) com sucesso.");
		
		return redirect(Pages.MANTER_PESSOA);
		
	}
	
	/**
	 * 
	 * @param actionEvent
	 */
	public String ativarSelecionados(AjaxBehaviorEvent event) {
		
		if(modelPessoa.getSelecionados() == null || modelPessoa.getSelecionados().length <= 0){
			messageWarn("Nenhum registro foi selecionado.");
			return redirect(Pages.MANTER_PESSOA);
		}
		
		listarUsuarios();
		
		int qtd = modelPessoa.getUsuariosSelecionados().size();
		daoUsuario.desbloqueio(modelPessoa.getUsuariosSelecionados());
		messageInfo("Foi(ram) Bloqueado(s) "+qtd+" registro(s) com sucesso.");
		
		return redirect(Pages.MANTER_PESSOA);
		
	} 
	
	public void listarUsuarios(){
		
		List <Usuario> usuarios = new ArrayList();		
	
		for(Pessoa pessoa:modelPessoa.getSelecionados()) {
			
			for(Usuario usuario: modelPessoa.getUsuarios()) {
				
				if(pessoa.getCpfCnpj().toString().equals(usuario.getId().toString())) {
					usuarios.add(usuario);
				}
			}
		}
		modelPessoa.setUsuariosSelecionados(usuarios);
	}
	
	public Usuario buscaUsuario(String id) {
		
		Usuario usu = null;
		
		for(Usuario usuario :modelPessoa.getUsuarios()) {
			
			if(usuario.getId().trim().length()<11 || usuario.getId().trim().length()>11 || usuario.getId().trim().length()<14) {
				usuario.setId(adicionaZero(usuario.getId()));
			}
			
			if(usuario.getId().toString().equals(id)) {
				usu = usuario;
				break;
			}
		}
		
		return usu;
	}
	
	public StatusEnum[] getListaStatus(){
		return StatusEnum.values();
	}
	
	public String adicionaZero(String cpfCnpj){
	
		while(cpfCnpj.trim().length() <= 10) {
			cpfCnpj = "0" + cpfCnpj.toString();
			
		}
		
		while(cpfCnpj.trim().length() > 11 && cpfCnpj.trim().length() <=13) {
			cpfCnpj = "0" + cpfCnpj.toString();
			
		}
		
		return cpfCnpj;
	}

}

sistema/src/main/webapp/WEB-INF/page/manterimoveis/manter_imoveis_alterar.xhtml
<ui:composition template="/templates/layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="centroMeio">
		<p:panelGrid columns="1" style="margin:0 auto;width:100%;">

			<f:facet name="header">
			#{msg['imoveis_menu_alterar']}
		</f:facet>


			<h:form id="detailForm">
				<p:growl autoUpdate="true" globalOnly="true" sticky="false" />
				<p:panelGrid id="display" columns="2" cellpadding="4"
					style="margin:0 auto;">
					
					<h:outputText value="#{msg['imoveis_id']} :" />
					<h:panelGroup>
						<h:message for="itid" styleClass="error" />
						<h:inputText maxlength="8" size="21"
							required="true" id="itid" label="#{msg['imoveis_id']}"
							value="#{modelImoveis.imovelSelecionado.id}"
							readonly="true">
						</h:inputText>
					</h:panelGroup>

					<h:outputText value="#{msg['imoveis_tipo']} :" />
					<h:panelGroup>
						<h:message for="itTpImovel" styleClass="error"  />
						<h:selectOneMenu id="itTpImovel" required="true" 
						style="width: 160px; height: 30px;"
							value="#{modelImoveis.tpImovel}">
							<f:selectItems value="#{modelImoveis.listatpImoveis}" var="_item"
								itemValue="#{_item}" itemLabel="#{_item.tipo}" />
						</h:selectOneMenu>
					</h:panelGroup>


					<h:outputText value="#{msg['imoveis_status']} :" />
					<h:panelGroup>
						<h:message for="itStatus" styleClass="error" />
						<h:selectOneMenu id="itStatus" required="true"
						style="width: 160px; height: 30px;"
							value="#{modelImoveis.statusImovel}">
							<f:selectItems value="#{modelImoveis.listaStatusImoveis}"
								var="_item" itemValue="#{_item}" itemLabel="#{_item.status}" />
						</h:selectOneMenu>
					</h:panelGroup>

					<h:outputText value="#{msg['imoveis_descricao']} :" />
					<h:panelGroup>
						<h:message for="itDesc" styleClass="error" />
						<h:inputText style="width: 160px; height: 30px;" maxlength="2000"
							id="itDesc" label="#{msg['imoveis_descricao']}"
							value="#{modelImoveis.imovelSelecionado.dsImovel}" required="true">
							<f:converter converterId="br.com.vle.util.CaixaAltaConverter" />
						</h:inputText>
					</h:panelGroup>

					<h:outputText value="#{msg['imoveis_observacoes']} :" />
					<h:panelGroup>
						<h:message for="itObs" styleClass="error" />
						<h:inputText style="width: 160px; height: 30px;" maxlength="2000"
							required="true" id="itObs" label="#{msg['imoveis_observacoes']}"
							value="#{modelImoveis.imovelSelecionado.dsObservacoes}">
							<f:converter converterId="br.com.vle.util.CaixaAltaConverter" />
						</h:inputText>
					</h:panelGroup>

					<h:outputText value="#{msg['imoveis_cep']} :" />
					<h:panelGroup>
						<h:message for="itCep" styleClass="error" />
						<h:inputText id="itCep" maxlength="8" size="21"
							label="#{msg['imoveis_cep']}" value="#{modelImoveis.imovelSelecionado.cep}"
							required="true">
						</h:inputText>
						<p:commandButton icon="ui-icon-search" update="detailForm"
							action="#{alterarImoveisController.buscarEndereco()}"
							title="#{msg['pessoa_acao_buscar_endereco']}">
						</p:commandButton>
					</h:panelGroup>

					<h:outputText value="#{msg['imoveis_logradouro']} :" />
					<h:panelGroup>
						<h:message for="itLogradouro" styleClass="error" />
						<h:inputText id="itLogradouro" maxlength="50" size="51"
							label="#{msg['imoveis_logradouro']}"
							value="#{modelImoveis.imovelSelecionado.logradouro}" required="true"
							readonly="false">
							<f:converter converterId="br.com.vle.util.CaixaAltaConverter" />
						</h:inputText>
					</h:panelGroup>

					<h:outputText value="#{msg['imoveis_complemento']} :" />
					<h:panelGroup>
						<h:message for="itComplemento" styleClass="error" />
						<h:inputText id="itComplemento" maxlength="50" size="51"
							label="#{msg['imoveis_complemento']}"
							value="#{modelImoveis.imovelSelecionado.complemento}" required="true">
							<f:converter converterId="br.com.vle.util.CaixaAltaConverter" />
						</h:inputText>
					</h:panelGroup>

					<h:outputText value="#{msg['imoveis_numero']} :" />
					<h:panelGroup>
						<h:message for="itNumero" styleClass="error" />
						<h:inputText id="itNumero" maxlength="10" size="21"
							label="#{msg['imoveis_numero']}"
							value="#{modelImoveis.imovelSelecionado.numero}" required="true">
						</h:inputText>
					</h:panelGroup>

					<h:outputText value="#{msg['imoveis_bairro']} :" />
					<h:panelGroup>
						<h:message for="itBairro" styleClass="error" />
						<h:inputText id="itBairro" maxlength="20" size="21"
							label="#{msg['imoveis_bairro']}"
							value="#{modelImoveis.imovelSelecionado.bairro}" required="true"
							readonly="false">
							<f:converter converterId="br.com.vle.util.CaixaAltaConverter" />
						</h:inputText>
					</h:panelGroup>

					<h:outputText value="#{msg['imoveis_localidade']} :" />
					<h:panelGroup>
						<h:message for="itLocalidade" styleClass="error" />
						<h:inputText id="itLocalidade" maxlength="20" size="21"
							label="#{msg['imoveis_localidade']}"
							value="#{modelImoveis.imovelSelecionado.localidade}" required="true"
							readonly="false">
							<f:converter converterId="br.com.vle.util.CaixaAltaConverter" />
						</h:inputText>
					</h:panelGroup>

					<h:outputText value="#{msg['imoveis_uf']} :" />
					<h:panelGroup>
						<h:message for="itUf" styleClass="error" />
						<h:inputText id="itUf" maxlength="2" size="21"
							label="#{msg['imoveis_uf']}" value="#{modelImoveis.imovelSelecionado.uf}"
							required="true" readonly="false">
							<f:converter converterId="br.com.vle.util.CaixaAltaConverter" />
						</h:inputText>
					</h:panelGroup>

					<f:facet name="footer">

						<p:commandButton value="#{msg['imoveis_acao_salvar']}"
							action="#{alterarImoveisController.alterar()}" update="detailForm"
							title="#{msg['pessoa_acao_salvar_title']}">
						</p:commandButton>

						<p:commandButton value="#{msg['voltar']}" immediate="true"
							action="#{alterarImoveisController.voltar(true)}"
							title="#{msg['voltar_title']}">
						</p:commandButton>

					</f:facet>


				</p:panelGrid>

			</h:form>
		</p:panelGrid>
	</ui:define>

	<ui:define name="centroRodapeSemLayout" />
	<ui:define name="direitaSemLayout" />

</ui:composition>

sistema/src/main/webapp/WEB-INF/page/manterimoveis/manter_imoveis_detalhar.xhtml
<ui:composition template="/templates/layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="centroMeio">
		<p:panelGrid columns="1" style="margin:0 auto;width:100%;">

			<f:facet name="header">
			#{msg['imoveis_menu_detalhar']}
		</f:facet>


			<h:form id="detailForm">
				<p:growl autoUpdate="true" globalOnly="true" sticky="false" />
				<p:panelGrid id="display" columns="2" cellpadding="4"
					style="margin:0 auto;">
					
					<h:outputText value="#{msg['imoveis_id']} :" />
					<h:panelGroup>
						<h:message for="itId" styleClass="error" />
						<h:inputText id="itId" maxlength="8" size="21" 
							label="#{msg['imoveis_id']}"
							value="#{modelImoveis.imovelSelecionado.id}"
							readonly="true">
						</h:inputText>
					</h:panelGroup>

					<h:outputText value="#{msg['imoveis_tipo']} :" />
					<h:panelGroup>
						<h:message for="itTpImovel" styleClass="error"  />
						<h:selectOneMenu id="itTpImovel" required="true" 
						style="width: 160px; height: 30px;"
							value="#{modelImoveis.tpImovel}">
							<f:selectItems value="#{modelImoveis.listatpImoveis}" var="_item"
								itemValue="#{_item}" itemLabel="#{_item.tipo}" />
						</h:selectOneMenu>
					</h:panelGroup>


					<h:outputText value="#{msg['imoveis_status']} :" />
					<h:panelGroup>
						<h:message for="itStatus" styleClass="error" />
						<h:selectOneMenu id="itStatus" required="true"
						style="width: 160px; height: 30px;"
							value="#{modelImoveis.statusImovel}">
							<f:selectItems value="#{modelImoveis.listaStatusImoveis}"
								var="_item" itemValue="#{_item}" itemLabel="#{_item.status}" />
						</h:selectOneMenu>
					</h:panelGroup>

					<h:outputText value="#{msg['imoveis_descricao']} :" />
					<h:panelGroup>
						<h:message for="itDesc" styleClass="error" />
						<h:inputText style="width: 160px; height: 30px;" maxlength="2000"
							id="itDesc" label="#{msg['imoveis_descricao']}"
							value="#{modelImoveis.imovelSelecionado.dsImovel}" required="true">
							<f:converter converterId="br.com.vle.util.CaixaAltaConverter" />
						</h:inputText>
					</h:panelGroup>

					<h:outputText value="#{msg['imoveis_observacoes']} :" />
					<h:panelGroup>
						<h:message for="itObs" styleClass="error" />
						<h:inputText style="width: 160px; height: 30px;" maxlength="2000"
							required="true" id="itObs" label="#{msg['imoveis_observacoes']}"
							value="#{modelImoveis.imovelSelecionado.dsObservacoes}">
							<f:converter converterId="br.com.vle.util.CaixaAltaConverter" />
						</h:inputText>
					</h:panelGroup>

					<h:outputText value="#{msg['imoveis_cep']} :" />
					<h:panelGroup>
						<h:message for="itCep" styleClass="error" />
						<h:inputText id="itCep" maxlength="8" size="21"
							label="#{msg['imoveis_cep']}" value="#{modelImoveis.imovelSelecionado.cep}"
							required="true">
						</h:inputText>
					</h:panelGroup>

					<h:outputText value="#{msg['imoveis_logradouro']} :" />
					<h:panelGroup>
						<h:message for="itLogradouro" styleClass="error" />
						<h:inputText id="itLogradouro" maxlength="50" size="51"
							label="#{msg['imoveis_logradouro']}"
							value="#{modelImoveis.imovelSelecionado.logradouro}" required="true"
							readonly="false">
							<f:converter converterId="br.com.vle.util.CaixaAltaConverter" />
						</h:inputText>
					</h:panelGroup>

					<h:outputText value="#{msg['imoveis_complemento']} :" />
					<h:panelGroup>
						<h:message for="itComplemento" styleClass="error" />
						<h:inputText id="itComplemento" maxlength="50" size="51"
							label="#{msg['imoveis_complemento']}"
							value="#{modelImoveis.imovelSelecionado.complemento}" required="true">
							<f:converter converterId="br.com.vle.util.CaixaAltaConverter" />
						</h:inputText>
					</h:panelGroup>

					<h:outputText value="#{msg['imoveis_numero']} :" />
					<h:panelGroup>
						<h:message for="itNumero" styleClass="error" />
						<h:inputText id="itNumero" maxlength="10" size="21"
							label="#{msg['imoveis_numero']}"
							value="#{modelImoveis.imovelSelecionado.numero}" required="true">
						</h:inputText>
					</h:panelGroup>

					<h:outputText value="#{msg['imoveis_bairro']} :" />
					<h:panelGroup>
						<h:message for="itBairro" styleClass="error" />
						<h:inputText id="itBairro" maxlength="20" size="21"
							label="#{msg['imoveis_bairro']}"
							value="#{modelImoveis.imovelSelecionado.bairro}" required="true"
							readonly="false">
							<f:converter converterId="br.com.vle.util.CaixaAltaConverter" />
						</h:inputText>
					</h:panelGroup>

					<h:outputText value="#{msg['imoveis_localidade']} :" />
					<h:panelGroup>
						<h:message for="itLocalidade" styleClass="error" />
						<h:inputText id="itLocalidade" maxlength="20" size="21"
							label="#{msg['imoveis_localidade']}"
							value="#{modelImoveis.imovelSelecionado.localidade}" required="true"
							readonly="false">
							<f:converter converterId="br.com.vle.util.CaixaAltaConverter" />
						</h:inputText>
					</h:panelGroup>

					<h:outputText value="#{msg['imoveis_uf']} :" />
					<h:panelGroup>
						<h:message for="itUf" styleClass="error" />
						<h:inputText id="itUf" maxlength="2" size="21"
							label="#{msg['imoveis_uf']}" value="#{modelImoveis.imovelSelecionado.uf}"
							required="true" readonly="false">
							<f:converter converterId="br.com.vle.util.CaixaAltaConverter" />
						</h:inputText>
					</h:panelGroup>

					<f:facet name="footer">

						<p:commandButton value="#{msg['voltar']}" immediate="true"
							action="#{imoveisController.fechaDetalhe()}"
							title="#{msg['voltar_title']}">
						</p:commandButton>

					</f:facet>


				</p:panelGrid>

			</h:form>
		</p:panelGrid>
	</ui:define>

	<ui:define name="centroRodapeSemLayout" />
	<ui:define name="direitaSemLayout" />

</ui:composition>